trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'your-auto-populated-service-connection-number'
  azureSubscriptionName: 'your-azure-subscription-name'
  dockerfilePath: '$(Build.SourcesDirectory)/dotnet-framework-wc-devops/taskapp/taskapp/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        # repository: '$(imageRepository)'
        dockerfile: $(dockerfilePath)
        # containerRegistry: '$(dockerRegistryServiceConnection)'
        buildContext: $(Build.SourcesDirectory)/dotnet-framework-wc-devops
        tags: |
          $(tag)
  